name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        find-dir: examples/
        output-file: README.md
        output-method: inject
        git-push: "true"
  
    - name: Render terraform docs for microsoft365_graph and push changes back to PR
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        find-dir: examples/microsoft365_graph/
        output-file: README.md
        output-method: inject
        git-push: "true"

    - name: Render terraform docs for microsoft365_graph_beta and push changes back to PR
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        find-dir: examples/microsoft365_graph_beta/
        output-file: README.md
        output-method: inject
        git-push: "true"